networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend
      - frontend
      - adminzakaz
    networks:
      - dev

  backend:
    build:
      context: ./itog/backend
    networks:
      - dev
      
  frontend:
    build:
      context: ./itog/frontend
    networks:
      - dev

  adminzakaz:
    build:
      context: ./adminzakaz
    networks:
      - dev